### ISSUE TITLE
Types Failing For Deno Setup

### ISSUE THREAD

**Issue by derekdowling** [rhinobase/hono-openapi#20]
Hello,

Very excited about this project! The ergonomics are a lot better than the other options. However, a basic hello world setup based on [this guide](https://hono.dev/examples/hono-openapi) and [Deno](2.1.4) seems to have type issues.

Library versions:
```
  "imports": {
    "@hono/zod-validator": "npm:@hono/zod-validator@^0.4.1",
    "@scalar/hono-api-reference": "npm:@scalar/hono-api-reference@^0.5.164",
    "hono-openapi": "npm:hono-openapi@^0.2.1",
    "zod": "npm:zod@^3.24.1",
    "zod-openapi": "npm:zod-openapi@^4.1.0"
  },
```

App:

```
import { Hono, type MiddlewareHandler } from "hono";
import { openAPISpecs } from "hono-openapi";
import { apiReference } from "@scalar/hono-api-reference";
// import { healthCheck } from "./route-groups/health/index.ts";

export const app = new Hono();
// .route("/health-check", healthCheck);

app.get(
  "/openapi",
  openAPISpecs(app, {
    documentation: {
      info: {
        title: "Commerce Service API",
        version: "0.0.1",
        description: "Greeting API",
      },
      servers: [
        {
          url: "http://localhost:8000",
          description: "Local Server",
        },
      ],
    },
    // deno-lint-ignore no-explicit-any
  }) as unknown as MiddlewareHandler<any>,
);

app.get(
  "/docs",
  apiReference({
    spec: { url: "/openapi" },
  }),
);
```

Running `deno check **/*.ts` produces:

```
error: TS2589 [ERROR]: Type instantiation is excessively deep and possibly infinite.
  openAPISpecs(app, {
  ^
    at file:///.../app.ts:11:3

TS2769 [ERROR]: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env>' is not assignable to parameter of type 'H<BlankEnv, "/docs", BlankInput, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env>' is not assignable to type 'MiddlewareHandler<BlankEnv, "/docs", BlankInput>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<BlankEnv, "/docs", BlankInput>' is not assignable to type 'Context<Env, string, {}>'.
            Types of property 'env' are incompatible.
              Type 'unknown' is not assignable to type 'object | undefined'.
  apiReference({
  ^
    at file:///.../app.ts:31:3

TS2771 [ERROR]:     The last overload is declared here.
        at file:///.../Library/Caches/deno/npm/registry.npmjs.org/hono/4.6.14/dist/types/types.d.ts:389:5
```
        
And for a very basic route:
```
import { Hono } from "hono";
import { z } from "zod";
import { describeRoute } from "hono-openapi";
import { resolver } from "hono-openapi/zod";

import "zod-openapi/extend";

// const querySchema = z.object({});

const responseSchema = z.object({
  status: z.literal("ok"),
});

export const healthCheck = new Hono().get(
  "/",
  describeRoute({
    description: "Health check",
    responses: {
      200: {
        description: "OK",
        content: {
          "application/json": {
            schema: resolver(responseSchema),
          },
        },
      },
    },
  }),
  (c) => {
    return c.json({ status: "ok" });
  },
);
```
  
I am seeing:
```
TS2769 [ERROR]: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, Input>' is not assignable to parameter of type 'H<BlankEnv, "/", BlankInput, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env, string, Input>' is not assignable to type 'MiddlewareHandler<BlankEnv, "/", BlankInput>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<BlankEnv, "/", BlankInput>' is not assignable to type 'Context<Env, string, Input>'.
            Types of property 'env' are incompatible.
              Type 'unknown' is not assignable to type 'object | undefined'.
  describeRoute({
  ^
    at file://.../health/index.ts:16:3
```      

I'm brand new to Deno and Hono, so I'm not really sure if there is a good way to work around this in the short term. Is there some sort of collision of types happening maybe?

**Comment by MathurAditya724** [comment]
I think this is related to the `jsr` types of `hono` conflicting with the `hono-openapi`. To solve this I just import `hono` from `npm`. Like this - 

```ts
// main.ts
import { Hono } from "hono";
import { describeRoute } from "hono-openapi";

const app = new Hono();

app.get(
  "/",
  describeRoute({
    description: "A simple hello world route",
  }),
  (c) => {
    return c.text("Hello Hono!");
  }
);

Deno.serve(app.fetch);
```
And this is how my `deno.json` looks like -
```json
{
  "tasks": {
    "start": "deno run --allow-net main.ts"
  },
  "compilerOptions": {
    "jsx": "precompile",
    "jsxImportSource": "hono/jsx"
  },
  "imports": {
    "hono": "npm:hono@^4.6.14",
    "hono-openapi": "npm:hono-openapi@^0.2.1"
  }
}
```
Let me know if this solves your issue.

**Comment by derekdowling** [comment]
To close the loop, it was indeed a type collision from mixing npm and jsr dependencies together. @MathurAditya724 thanks for the help! I'll watch out for that moving forward.

I'm still hitting a types issue with `import { apiReference } from "@scalar/hono-api-reference";`, but I'll take up with the Scalar project 😄

**Comment by MathurAditya724** [comment]
Glad to hear the solution worked for you! 😊

If there's nothing else, would it be okay to close this issue?
